version: "3"
services:
  testContainer1:
    image: bakanai/node-web-app
    ports:
      - "8081:80"
    restart: always
    networks:
      test:
        ipv4_address: 192.168.92.21
  testContainer2:
    image: bakanai/node-web-app
    ports:
      - "8082:80"
    restart: always
    networks:
      test:
        ipv4_address: 192.168.92.22
networks:
  test:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"